import {
  HomeIcon,
  BuildingOfficeIcon,
  HomeModernIcon,
  CameraIcon,
  FireIcon,
  BeakerIcon,
  BuildingLibraryIcon,
  CakeIcon,
  SunIcon,
  WifiIcon,
  MapIcon,
  GlobeAsiaAustraliaIcon,
  ArrowPathIcon,
  CloudIcon,
  HeartIcon,
  StarIcon,
  TrophyIcon,
  SparklesIcon,
} from '@heroicons/react/24/outline';

export const categories = [
  { name: '인기 급상승', icon: FireIcon },
  { name: '한옥', icon: HomeModernIcon },
  { name: '해변 근처', icon: WifiIcon },
  { name: '최고의 전망', icon: CameraIcon },
  { name: '료칸', icon: HomeModernIcon },
  { name: '캐슬', icon: BuildingLibraryIcon },
  { name: '열대지역', icon: SunIcon },
  { name: '국립공원', icon: MapIcon },
  { name: '섬', icon: GlobeAsiaAustraliaIcon },
  { name: '수영장', icon: ArrowPathIcon },
  { name: '스키장', icon: CloudIcon },
  { name: '디자인하우스', icon: SparklesIcon },
  { name: '초소형 주택', icon: HomeIcon },
  { name: '신규', icon: SparklesIcon },
  { name: '저택', icon: BuildingOfficeIcon },
  { name: '키즈 친화적', icon: HeartIcon },
  { name: '최고 평점', icon: StarIcon },
  { name: '슈퍼호스트', icon: TrophyIcon },
  { name: '럭셔리', icon: SparklesIcon },
  { name: '트리하우스', icon: MapIcon },
  { name: '통나무집', icon: HomeIcon },
  { name: '캠핑장', icon: MapIcon },
  { name: '농장', icon: HomeModernIcon },
  { name: '북극', icon: CloudIcon },
  { name: '사막', icon: SunIcon },
  { name: '동굴', icon: CloudIcon },
  { name: 'B&B', icon: CakeIcon },
  { name: '우주정거장', icon: SparklesIcon },
  { name: '기상천외한 숙소', icon: BeakerIcon },
].map((category) => ({
  ...category,
  value: category.name === '인기 급상승' ? 'trending' : encodeURIComponent(category.name),
}));
